const BPPCONFIRMSCHEMA = require("./BPPCONFIRMSCHEMA");
const BPPINITSCHEMA = require("./BPPINITSCHEMA");
const BPPSEARCHSCHEMA = require("./BPPSEARCHSCHEMA");
const BPPSELECTSCHEMA = require("./BPPSELECTSCHEMA");
const BPPSTATUSSCHEMA = require("./BPPSTATUSSCHEMA");

module.exports={
    BPPSEARCHSCHEMA,
    BPPSELECTSCHEMA,
    BPPINITSCHEMA,
    BPPCONFIRMSCHEMA,
    BPPSTATUSSCHEMA
}