const BPPCONFIRMSCHEMA = require("./BPPCONFIRMSCHEMA");
const BPPINITSCHEMA = require("./BPPINITSCHEMA");
const BPPSEARCHSCHEMA = require("./BPPSEARCHSCHEMA");
const BPPSELECTSCHEMA = require("./BPPSELECTSCHEMA");

module.exports={
    BPPSEARCHSCHEMA,
    BPPSELECTSCHEMA,
    BPPINITSCHEMA,
    BPPCONFIRMSCHEMA
}