const  BAPCONFIRMSCHEMA = require("./BAPCONFIRMSCHEMA");
const BAPINITSCHEMA  = require("./BAPINITSCHEMA");
const BAPSEARCHSCHEMA = require("./BAPSEARCHSCHEMA");
const BAPSELECTSCHEMA = require("./BAPSELECTSCHEMA");
const BAPSTATUSSCHEMA = require("./BAPSTATUSSCHEMA");

module.exports={
    BAPSEARCHSCHEMA,
    BAPSELECTSCHEMA,
    BAPINITSCHEMA,
    BAPCONFIRMSCHEMA,
    BAPSTATUSSCHEMA
}